name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 0 * * *'


env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Build no_std
      run: cargo build --verbose --no-default-features
    - name: Build use_std
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: cargo clippy --verbose
